use_frameworks!

platform :ios, '8.0'

target 'SDKDemo' do
  pod 'WCDB'
  pod 'Protobuf'
  pod 'YYModel'
  
#  UI依赖
  pod 'IQKeyboardManager', '5.0.8'
  pod 'SDWebImage', '4.2.3'
  pod 'Masonry'
  pod 'MBProgressHUD', '0.9.2'
end
