use_frameworks!

platform :ios, '8.0'

target 'SDKDemo' do
#  pod 'WCDB'
#  pod 'Protobuf'
  pod 'YYModel'
  
#  UI依赖
  pod 'IQKeyboardManager', '5.0.8'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MBProgressHUD', '0.9.2'
#  pod 'TXIMSDK_TUIKit_iOS'
#  pod 'ISVImageScrollView', '~> 0.2.0'
#  pod 'TXIMSDK_iOS' ,'~> 4.8.10'
end
