source 'https://github.com/leshiguang/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'SDKDemo' do
  pod 'LSBluetoothUI_iOS', '0.4.1'
  pod 'LZBluetooth', '1.6.2'
end
